In [47]:
# import torch module
import torch
# create a 3 D tensor with 8 elements each
a = torch.tensor([
    [
        [1, 2, 3, 4, 5, 6, 7, 8],
        [10, 11, 12, 13, 14, 15, 16, 17]
    ],
    [
        [71, 72, 73, 74, 75, 76, 77, 78],
        [81, 82, 83, 84, 85, 86, 87, 88]
    ]
    ])
# display actual tensor

#tensor([1, 2, 3, 4, 5, 6, 7])
print(a[0, 0, :-1])

#tensor([[ 1, 2, 3], [10, 11, 12]])
print(a[0, :, :3])

tensor([1, 2, 3, 4, 5, 6, 7])
tensor([[ 1,  2,  3],
        [10, 11, 12]])


In [57]:
import torch
x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0, requires_grad=True)
# forward pass and compute the loss
y_hat = w * x
loss = (y_hat - y)**2
print(loss)
# backward pass
loss.backward()
print(w.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


In [ ]:
import torch

x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0, requires_grad=True)
learning_rate = 0.1

for epoch in range(20):
    loss = (w * x - y) ** 2
    loss.backward()
    
    w.data -= learning_rate * w.grad
    
    w.grad.zero_()
    
    print(f"Iteración {epoch+1}: w = {w.item():.2f}, Pérdida = {loss.item():.4f}")

Iteración 1: w = 1.20, Pérdida = 1.0000
Iteración 2: w = 1.36, Pérdida = 0.6400
Iteración 3: w = 1.49, Pérdida = 0.4096
Iteración 4: w = 1.59, Pérdida = 0.2621
Iteración 5: w = 1.67, Pérdida = 0.1678
Iteración 6: w = 1.74, Pérdida = 0.1074
Iteración 7: w = 1.79, Pérdida = 0.0687
Iteración 8: w = 1.83, Pérdida = 0.0440
Iteración 9: w = 1.87, Pérdida = 0.0281
Iteración 10: w = 1.89, Pérdida = 0.0180
Iteración 11: w = 1.91, Pérdida = 0.0115
Iteración 12: w = 1.93, Pérdida = 0.0074
Iteración 13: w = 1.95, Pérdida = 0.0047
Iteración 14: w = 1.96, Pérdida = 0.0030
Iteración 15: w = 1.96, Pérdida = 0.0019
Iteración 16: w = 1.97, Pérdida = 0.0012
Iteración 17: w = 1.98, Pérdida = 0.0008
Iteración 18: w = 1.98, Pérdida = 0.0005
Iteración 19: w = 1.99, Pérdida = 0.0003
Iteración 20: w = 1.99, Pérdida = 0.0002
